### ISSUE TITLE
is there a way to lower case the title in jekyll?

### ISSUE THREAD

**Issue by abelsonlive** [csvsoundsystem/csv.nyc#3]
cant seem to find reference. this does not fit our style guide:

![screenshot 2014-08-04 20 23 08](https://cloud.githubusercontent.com/assets/1621721/3805453/c58875c2-1c36-11e4-9979-704c96fa6aa6.png)

**Comment by mhkeller** [comment]
+1

**Comment by feitla** [comment]
yeah, use downcase `{{ 'UPPERCASE' | downcase }}`
